apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-java-client
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubernetes-java-client
  template:
    metadata:
      labels:
        app: kubernetes-java-client
    spec:
      containers:
      - image: kubernetes-java-client:1.0
        imagePullPolicy: IfNotPresent
        name: kubernetes-java-client
        ports:
          - containerPort: 8080