apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: ms-admin
  name: ms-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: ms-admin
  name: ms-admin
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - pods
  - replicasets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: ms-admin
  name: ms-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ms-admin
subjects:
- kind: ServiceAccount
  name: ms-admin
